/*****************************************************************************
**   C A U T I O N                                                          **
**   This file is auto-generated!                                           **
**   If you want to make changes, please see the README.md file.            **
**   Please do not edit this file directly!                                 **
*****************************************************************************/
package de.lancom.openapi.parser.serialisation

import de.lancom.openapi.parser.entity.AdditionalPropertiesSchema
import de.lancom.openapi.parser.serialisation.testcases.*
import org.junit.jupiter.params.provider.Arguments
import java.util.stream.Stream

// hint:6E7C2D8B
class AdditionalPropertiesSchemaSerialisationTest : AbstractSerialisationTest() {
    companion object {

        const val emptyYaml = "{}"
        val emptySubject = de.lancom.openapi.parser.entity.AdditionalProperties(de.lancom.openapi.parser.entity.Schema())

        private val testCases: List<TestCase<AdditionalPropertiesSchema>> = entityFieldTestCases(
            emptyYaml = emptyYaml,
            emptySubject = emptySubject,
            fieldTests = listOf(
            )
        )

        @JvmStatic
        fun testCases(): Stream<Arguments> {
            return testCases.toArgumentsStream()
        }
    }
}
